# Generated by Django 4.2.30 on 2026-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_rating_add_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestation',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Місто'),
        ),
    ]
