# Generated by Django 4.2.30 on 2026-06-10 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicestation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestation',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Власник'),
        ),
    ]
