# Generated by Django 4.2.30 on 2026-06-20 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_create_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.car', verbose_name='Автомобіль'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва послуги'),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='closing_time',
            field=models.TimeField(default='18:00', verbose_name='Час закриття'),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='opening_time',
            field=models.TimeField(default='09:00', verbose_name='Час відкриття'),
        ),
    ]
