# Generated by Django 4.2.30 on 2026-07-02 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_booking_car_booking_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.car', verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Бажаний час візиту'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='station',
            field=models.ForeignKey(db_column='station_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.servicestation', verbose_name='СТО'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(main.models.get_current_year_plus_one)], verbose_name='Рік випуску'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клієнт'), ('station', 'Адміністратор СТО')], db_index=True, max_length=10, verbose_name='Роль'),
        ),
    ]
