# Generated by Django 4.2.30 on 2026-07-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(default=60, verbose_name='Тривалість (хвилин)'),
        ),
        migrations.CreateModel(
            name='StationBox',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Назва боксу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='main.servicestation', verbose_name='СТО')),
            ],
            options={
                'verbose_name': 'Робочий бокс',
                'verbose_name_plural': 'Робочі бокси',
                'db_table': 'station_box',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='box',
            field=models.ForeignKey(blank=True, db_column='box_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.stationbox', verbose_name='Робочий бокс'),
        ),
    ]
