# Generated by Django 4.2.30 on 2026-07-22 13:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_booking_duration_stationbox_booking_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата обслуговування')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробіг (км)')),
                ('work_list', models.TextField(verbose_name='Перелік виконаних робіт')),
                ('spare_parts', models.TextField(blank=True, null=True, verbose_name='Використані запчастини')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Підсумкова вартість (грн)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запису')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_history_records', to='main.booking', verbose_name='Заявка')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='main.car', verbose_name='Автомобіль')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_history_records', to='main.servicestation', verbose_name='СТО')),
            ],
            options={
                'verbose_name': 'Запис історії обслуговування',
                'verbose_name_plural': 'Історія обслуговування',
                'db_table': 'car_history',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
