# Generated by Django 4.2.30 on 2026-07-22 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_carhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст повідомлення')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_photos/', verbose_name='Фото несправності')),
                ('proposed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Запропонована додаткова вартість (грн)')),
                ('is_approved', models.BooleanField(blank=True, null=True, verbose_name='Статус узгодження клієнтом')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='main.booking', verbose_name='Заявка')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
            ],
            options={
                'verbose_name': 'Повідомлення чату',
                'verbose_name_plural': 'Повідомлення чату',
                'db_table': 'booking_chat_message',
                'ordering': ['created_at'],
            },
        ),
    ]
