# Generated by Django 4.2.30 on 2026-07-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_bookingchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestation',
            name='bank_details',
            field=models.TextField(blank=True, null=True, verbose_name='Банківські реквізити (IBAN/Банк)'),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='edrpou',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ЄДРПОУ / ІПН'),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридична адреса'),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='station_logos/', verbose_name='Логотип СТО'),
        ),
    ]
