# Generated by Django 4.2.30 on 2026-07-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_servicestation_bank_details_servicestation_edrpou_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')], verbose_name='День тижня')),
                ('is_working', models.BooleanField(default=True, verbose_name='Робочий день')),
                ('opening_time', models.TimeField(default='09:00', verbose_name='Час відкриття')),
                ('closing_time', models.TimeField(default='18:00', verbose_name='Час закриття')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Початок обіду')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Кінець обіду')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.servicestation', verbose_name='СТО')),
            ],
            options={
                'verbose_name': 'Графік роботи СТО',
                'verbose_name_plural': 'Графіки роботи СТО',
                'db_table': 'station_schedule',
                'ordering': ['day_of_week'],
                'unique_together': {('station', 'day_of_week')},
            },
        ),
    ]
