# Generated by Django 4.2.30 on 2026-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_stationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Об'єм / Двигун"),
        ),
    ]
