# Generated by Django 4.2.30 on 2026-07-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_car_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_response',
            field=models.TextField(blank=True, null=True, verbose_name='Відповідь автосервісу'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото відгуку'),
        ),
        migrations.AddField(
            model_name='review',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата відповіді СТО'),
        ),
    ]
