# Generated by Django 4.2.30 on 2026-09-28 21:18

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_station_service_search_norm_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bookingchatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='carhistory',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_name']},
        ),
        migrations.AlterModelOptions(
            name='stationbox',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stationschedule',
            options={'ordering': ['day_of_week']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='box',
            field=models.ForeignKey(blank=True, db_column='box_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.stationbox'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.car'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='station',
            field=models.ForeignKey(db_column='station_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.servicestation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingchatmessage',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='main.booking'),
        ),
        migrations.AlterField(
            model_name='bookingchatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookingchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_photos/'),
        ),
        migrations.AlterField(
            model_name='bookingchatmessage',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingchatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingchatmessage',
            name='proposed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingchatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingchatmessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='VIN має містити 17 символів (без літер I, O, Q).', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(main.models.get_current_year_plus_one)]),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_history_records', to='main.booking'),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='main.car'),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='spare_parts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_history_records', to='main.servicestation'),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='work_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.booking'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='station',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='main.servicestation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name_norm',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='station',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='main.servicestation'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='bank_details',
            field=models.TextField(blank=True, null=True, verbose_name='Банківські реквізити'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='city_norm',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='edrpou',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='station_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='name_norm',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='stationbox',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationbox',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stationbox',
            name='station',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='main.servicestation'),
        ),
        migrations.AlterField(
            model_name='stationschedule',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationschedule',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationschedule',
            name='closing_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='stationschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')]),
        ),
        migrations.AlterField(
            model_name='stationschedule',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stationschedule',
            name='opening_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='stationschedule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.servicestation'),
        ),
    ]
