# Generated by Django 4.2.30 on 2026-09-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_booking_base_work_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на обслуговування', 'verbose_name_plural': 'Заявки на обслуговування'},
        ),
        migrations.AlterModelOptions(
            name='bookingchatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Повідомлення в чаті', 'verbose_name_plural': 'Повідомлення в чаті'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-year'], 'verbose_name': 'Автомобіль', 'verbose_name_plural': 'Автомобілі'},
        ),
        migrations.AlterModelOptions(
            name='carhistory',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Запис історії авто', 'verbose_name_plural': 'Історія авто'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сповіщення', 'verbose_name_plural': 'Сповіщення'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date'], 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_name'], 'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterModelOptions(
            name='stationbox',
            options={'ordering': ['name'], 'verbose_name': 'Робочий бокс', 'verbose_name_plural': 'Робочі бокси'},
        ),
        migrations.AlterModelOptions(
            name='stationschedule',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Графік роботи', 'verbose_name_plural': 'Графіки роботи'},
        ),
    ]
