# Generated by Django 4.2.30 on 2026-06-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_remove_rating_add_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationPhoto',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='station_photos/', verbose_name='Фотографія')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='Підпис')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.servicestation', verbose_name='СТО')),
            ],
            options={
                'verbose_name': 'Фото СТО',
                'verbose_name_plural': 'Фото СТО',
                'db_table': 'station_photo',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
