# Generated by Django 4.2.30 on 2026-09-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_booking_options_and_more'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationphoto',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='photo',
            field=models.ImageField(upload_to='station_photos/'),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='station',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.servicestation'),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
