# Generated by Django 4.2.30 on 2026-09-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_stationphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationphoto',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Фотографія СТО', 'verbose_name_plural': 'Фотографії СТО'},
        ),
    ]
