# Generated by Django 4.2.30 on 2026-07-03 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0009_alter_booking_car_alter_booking_scheduled_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name="Повне ім'я")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ставка (грн)')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Комісія (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='main.servicestation', verbose_name='СТО')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
                'db_table': 'employee',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'Дохід'), ('expense', 'Витрата')], max_length=10, verbose_name='Тип')),
                ('category', models.CharField(choices=[('service', 'Послуги СТО (Дохід)'), ('other_income', 'Інші доходи'), ('salary', 'Виплата зарплати (Витрата)'), ('spare_parts', 'Запчастини (Витрата)'), ('rent', 'Оренда (Витрата)'), ('utilities', 'Комунальні послуги (Витрата)'), ('other_expense', 'Інші витрати')], max_length=20, verbose_name='Категорія')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума (грн)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.booking', verbose_name='Заявка')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.employee', verbose_name='Працівник')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.servicestation', verbose_name='СТО')),
            ],
            options={
                'verbose_name': 'Фінансова операція',
                'verbose_name_plural': 'Фінансові операції',
                'db_table': 'transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Всього зароблено')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Всього виплачено')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_balance', to='accounting.employee')),
            ],
            options={
                'verbose_name': 'Баланс зарплати',
                'verbose_name_plural': 'Баланси зарплат',
                'db_table': 'salary_balance',
            },
        ),
    ]
