# Generated by Django 4.2.30 on 2026-07-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_carhistory'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Назва запчастини/матеріалу')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул / Каталожний номер')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Собівартість (грн)')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна продажу (грн)')),
                ('min_quantity', models.PositiveIntegerField(default=5, verbose_name='Мінімальний залишок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='main.servicestation', verbose_name='СТО')),
            ],
            options={
                'verbose_name': 'Запчастина на складі',
                'verbose_name_plural': 'Запчастини на складі',
                'db_table': 'spare_part',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsedSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150, verbose_name='Назва деталі')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Використана кількість')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собівартість на момент використання (грн)')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу на момент використання (грн)')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_parts', to='main.booking', verbose_name='Заявка')),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_instances', to='accounting.sparepart', verbose_name='Запчастина')),
            ],
            options={
                'verbose_name': 'Використана запчастина',
                'verbose_name_plural': 'Використані запчастини',
                'db_table': 'used_spare_part',
            },
        ),
    ]
