# Generated by Django 4.2.30 on 2026-07-28 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_sparepart_usedsparepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Дохід'), ('expense', 'Витрата')], db_index=True, max_length=10, verbose_name='Тип'),
        ),
    ]
