# Generated by Django 4.2.30 on 2026-09-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_employee_options_alter_salarybalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedsparepart',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул'),
        ),
    ]
