# Generated by Django 4.2.30 on 2026-09-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_usedsparepart_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'Співробітник', 'verbose_name_plural': 'Співробітники'},
        ),
        migrations.AlterModelOptions(
            name='salarybalance',
            options={'verbose_name': 'Баланс заробітної плати', 'verbose_name_plural': 'Баланси заробітної плати'},
        ),
        migrations.AlterModelOptions(
            name='sparepart',
            options={'ordering': ['name'], 'verbose_name': 'Запчастина на складі', 'verbose_name_plural': 'Запчастини на складі'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Фінансова операція', 'verbose_name_plural': 'Фінансові операції'},
        ),
        migrations.AlterModelOptions(
            name='usedsparepart',
            options={'verbose_name': 'Використана деталь', 'verbose_name_plural': 'Використані деталі'},
        ),
    ]
